# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

permissions:
  checks: write

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      - name: Xcode Select Version
        uses: mobiledevops/xcode-select-version-action@v1
        with:
          xcode-select-version: 15.1
      - name: Run tests
        run: |
          xcodebuild test -project norr.xcodeproj -scheme norr -resultBundlePath NorrResults

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: NorrResults.xcresult